//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildCompany.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentRent
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Status { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdEquipment { get; set; }
        public Nullable<bool> Statuss { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual User User { get; set; }
    }
}
